[theme]
base = "dark"
primaryColor = "#6C63FF"
# Optional extras:
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#FAFAFA"
# font = "sans serif"  # or "serif", "monospace"
